server:
  port: 12345

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

      - id: report-service
        uri: lb://report-service
        predicates:
        - Path=/report/**
        filters:
        - RewritePath=/report/(?<path>.*), /$\{path}

      - id: account-service
        uri: lb://account-service
        predicates:
        - Path=/accounts/**
        filters:
        - RewritePath=/accounts/(<path>.*), /$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: spring-cloud
  resource: spring-cloud-api
  public-client: true
  security-constraints:
    - authRoles:
        - ROLE_SPRING_CLOUD
      securityCollections:
        - patterns:
            - /*